# Generated by Django 4.2.1 on 2023-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Names",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=35)),
                ("last", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=40)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
